### ISSUE TITLE
Getting an error when checking a field that contains a space

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-iterable#14]
**Steps to Reproduce:**
1. Create a scenario file
```yml
scenario: Iterable Contact API Test
description: This validates the behavior of Account creation, validation, and deletion.
  
steps:
- step: When I create or update an iterable contact
  data:
    contact:
          email: Itest@thisisjust.atomatest.com
          lastName: Wayne
          firstName: Bruce
          status: Single
          lifetimeValue: 250.12
          phoneNumber: "+639179535880"
          nick Name: BM
- step: Then the nick Name field on iterable contact Itest@thisisjust.atomatest.com should contain b
- step: Finally, delete the Itest@thisisjust.atomatest.com Iterable contact. 
```
**Actual Result:**
![image](https://user-images.githubusercontent.com/54615569/72617456-f56ff980-3973-11ea-82d7-eaf8abdaeb1a.png)

**Expected Result:**
![image](https://user-images.githubusercontent.com/54615569/72618395-ef7b1800-3975-11ea-9fbc-36b04141d7e7.png)
![image](https://user-images.githubusercontent.com/54615569/72617636-5ef00800-3974-11ea-946a-bd3d421ca81d.png)
The field should be able to be verified when using the scenario.
