### ISSUE TITLE
Cog should show error message content when present

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-iterable#18]
## Repro Steps
1. Run the following Scenario file:

```yml
scenario: Iterable Error Message
description: Should show more useful error details.

steps:
- step: When I create or update an Iterable Contact
  data:
    contact:
      email: error-message@thisisjust.atomatest.com
      dateofBirth: not a date
```

**Expected**: The scenario should result in an error and helpful details should be shown related to the fact that the data format on the `dateofBirth`.

**Actual**: The error message is non-specific `There was an error creating the Contact: Error: Request failed with status code 400`

![Screen Shot 2020-02-17 at 3 07 45 PM](https://user-images.githubusercontent.com/3496491/74691347-4b180b80-5197-11ea-92c4-1a1c17f37c19.png)

----

It looks like, on an error, the `error.response.data.msg` property contains potentially useful text.  e.g.

```
The request does not have the same data types as the data previously
submitted. Field 'dateofBirth' already exists for type 'user' and has a
data type of 'date' but possible types 'string, keyword' in the request.
```
