### ISSUE TITLE
Improve date field handling on contact creation

### ISSUE THREAD

**Issue by iamEAP** [run-crank/cog-iterable#19]
## Repro Steps
1. Run the following Scenario:

```yml
scenario: Iterable Date Field Creation
description:

tokens:
  testEmail: iterable-date-issue@thisisjust.atomatest.com

steps:
- step: When I create or update an Iterable Contact
  data:
    contact:
      email: '{{testEmail}}'
      firstName: Date
      lastName: Issue
      dateofBirth: 2000-01-01T00:00:00
- step: Then the dateofBirth field on Iterable Contact {{testEmail}} should be less than 2020-01-01T00:00:00
- step: Finally, delete the {{testEmail}} Iterable Contact
```

**Expected**: The above scenario should pass.

**Actual**: The scenario fails on the contact create step due to the fact that the input format does not fit Iterable's [narrow definition of acceptable date formats](https://support.iterable.com/hc/en-us/articles/208183076-Field-Data-Types#date).
