### ISSUE TITLE
Structured data records not appearing on failed step

### ISSUE THREAD

**Issue by roanlibelo** [run-crank/cog-iterable#22]
## Repro Steps:
```yml
scenario: Iterable Contact API Test
description: This validates the behavior of Account creation, validation, and deletion.
  
steps:
- step: When I create or update an iterable contact
  data:
    contact:
          email: Iteststructured@thisisjust.atomatest.com
          lastName: Wayne
          firstName: Bruce
          status: Single
          lifetimeValue: 250.12
          phoneNumber: "+639179535880"
          nick Name: BM
- step: Then the email field on iterable contact Iteststructured@thisisjust.atomatest.com should not contain google.com
- step: And the lastName field on iterable contact Iteststructured@thisisjust.atomatest.com should not be Wayne
- step: And the firstName field on iterable contact Iteststructured@thisisjust.atomatest.com should not be Wayne
- step: And the signupDate field on iterable contact Iteststructured@thisisjust.atomatest.com should be less than 2019-01-17 05:19:11 +00:00
- step: And the lifetimeValue field on iterable contact Iteststructured@thisisjust.atomatest.com should be less than 251
- step: And the phoneNumber field on iterable contact Iteststructured@thisisjust.atomatest.com should not be +69353165352
- step: And the nick Name field on iterable contact Iteststructured@thisisjust.atomatest.com should contain b
- step: Finally, delete the Iteststructured@thisisjust.atomatest.com Iterable contact. 
```

## Actual Result:
![image](https://user-images.githubusercontent.com/54615569/76060374-193add80-5fbc-11ea-8fc9-eda8cf3fa01c.png)

## Expected Result:
Structured data records should also appear when the step failed.
